--drop table T_EB_PaymentCheckResult;
---对账结果
CREATE TABLE T_EB_PaymentCheckResult(
	ID int primary key,
   	PAYMENT_ID int UNIQUE,--引用Payment
	CHECK_STATUS int,--对账状态 
	CHECK_STATUS_MSG NVARCHAR2(255),--对账附加说明
	DETAIL_ID int,--根据的detail id
	CREATE_TIME TIMESTAMP(6), 	
	UPDATE_TIME TIMESTAMP(6)
);
 
CREATE SEQUENCE PAYCHECK_RS_ID_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999 NOCYCLE NOCACHE;
