--drop table T_EB_Schedule;
CREATE TABLE T_EB_Schedule(
  	ID int PRIMARY KEY,
  	job_type VARCHAR2(20),
  	cron VARCHAR2(20),
  	params NVARCHAR2(1000),
  	STATUS	VARCHAR2(10) default 'enable',--状态:是否启用
	CREATE_TIME TIMESTAMP(6), 	
	UPDATE_TIME TIMESTAMP(6)
);
 
CREATE SEQUENCE SCHEDUAL_ID_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999 NOCYCLE NOCACHE;
