--drop table T_EB_FrontEnd;
CREATE TABLE T_EB_FrontEnd(
	ID int primary key,
	NAME NVARCHAR2(30) not null,--前置机配置名称
	BANK_NAME	VARCHAR2(10) not null,--银行简码
	STATUS	VARCHAR2(10) default 'enable',--状态:是否启用
	CREATE_TIME TIMESTAMP(6) not null,
	UPDATE_TIME TIMESTAMP(6)	
);
 CREATE SEQUENCE FRONTEND_ID_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999 NOCYCLE NOCACHE;
