--drop table T_EB_PaymentCheckRecord;
CREATE TABLE T_EB_PaymentCheckRecord(
  	ID int PRIMARY KEY,
  	ACC_NO  VARCHAR2(30) not null,  --交易主账号
	CHECK_DAY TIMESTAMP(0),--已对账的日期
	CREATE_TIME  TIMESTAMP(6),  --创建时间
  	UPDATE_TIME  TIMESTAMP(6)  --更新时间 
);
CREATE INDEX IDX_PAYCHECK_ACCNO on T_EB_PaymentCheckRecord(ACC_NO);
CREATE SEQUENCE PAYCHECK_ID_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999 NOCYCLE NOCACHE;
