--drop table T_EB_AccBalance;
CREATE TABLE T_EB_AccBalance(
  	ID int PRIMARY KEY,
  	BANK_NAME VARCHAR2(10), --银行名称
	ACC_NO VARCHAR2(30) not null,	--交易主账号
	BALANCE NUMBER(19,2), --付款金额
	AVAILABLE_BALANCE NUMBER(19,2), --付款金额
	CURRENCY char(5), --币别
	CREATE_TIME TIMESTAMP(6)	
);
 create INDEX IDX_BAL_ACCNO on T_EB_AccBalance(ACC_NO);
 CREATE SEQUENCE BALANCE_ID_SEQ INCREMENT BY 1 START WITH 1 MAXVALUE 999999999999999999 NOCYCLE NOCACHE;
 